--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATEST"."BOOK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "C##ATEST"."ADMIN" 
   (	"ADMIN_ID" NUMBER(5,0), 
	"PASSWORD" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "C##ATEST"."BOOK" 
   (	"TITLE" VARCHAR2(15 BYTE), 
	"AUTHOR" VARCHAR2(30 BYTE), 
	"PUBLISHER" VARCHAR2(30 BYTE), 
	"PUB_YEAR" NUMBER(4,0), 
	"BOOK_ID" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOOKS
--------------------------------------------------------

  CREATE TABLE "C##ATEST"."BOOKS" 
   (	"BOOK_ID" NUMBER(*,0), 
	"PUBLISHER_ID" VARCHAR2(5 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"AUTHOR" VARCHAR2(50 BYTE), 
	"ISBN" VARCHAR2(30 BYTE), 
	"NUM_OF_BOOKS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "C##ATEST"."CUSTOMER" 
   (	"CUST_ID" VARCHAR2(5 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL_ID" VARCHAR2(30 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"CONTACT" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "C##ATEST"."CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER(5,0), 
	"FIRST_NAME" VARCHAR2(10 BYTE), 
	"LAST_NAME" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(40 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ISSUE
--------------------------------------------------------

  CREATE TABLE "C##ATEST"."ISSUE" 
   (	"CUST_ID" VARCHAR2(5 BYTE), 
	"BOOK_ID" NUMBER(*,0), 
	"ISSUE_DATE" DATE, 
	"RETURN_DATE" DATE, 
	"STAFF_ID" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ISSUEHISTORY
--------------------------------------------------------

  CREATE TABLE "C##ATEST"."ISSUEHISTORY" 
   (	"BOOK_ID" VARCHAR2(5 BYTE), 
	"CUSTOMER_ID" NUMBER(5,0), 
	"STATUS" VARCHAR2(15 BYTE), 
	"BOOK_DATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PUBLISHER
--------------------------------------------------------

  CREATE TABLE "C##ATEST"."PUBLISHER" 
   (	"PUBLISHER_ID" VARCHAR2(5 BYTE), 
	"PUBLISHER_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "C##ATEST"."STAFF" 
   (	"STAFF_ID" VARCHAR2(5 BYTE), 
	"STAFF_NAME" VARCHAR2(30 BYTE), 
	"SALARY" NUMBER(8,2), 
	"PHONE" VARCHAR2(11 BYTE), 
	"STREET" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "C##ATEST"."TEST" 
   (	"NUM" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View ADMIN_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##ATEST"."ADMIN_VIEW" ("STAFF_ID", "STAFF_BRANCH_ID", "STAFF_NAME", "SALARY", "PHONE", "STREET", "B_ID", "BRANCH_STREET", "CITY") AS 
  SELECT "STAFF_ID","STAFF_BRANCH_ID","STAFF_NAME","SALARY","PHONE","STREET","B_ID","BRANCH_STREET","CITY"
FROM Staff,Branch 
WHERE Staff.Staff_Branch_ID=Branch.B_ID
;
--------------------------------------------------------
--  DDL for View CUSTOMER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##ATEST"."CUSTOMER_VIEW" ("TITLE", "AUTHOR", "NO_OF_BOOKS", "P_NAME") AS 
  SELECT Books.Title,Books.Author,Books.No_of_Books,Publisher.P_Name
FROM Publisher, Books
WHERE Publisher.P_ID=Books.Publisher_ID
;
REM INSERTING into C##ATEST.ADMIN
SET DEFINE OFF;
Insert into C##ATEST.ADMIN (ADMIN_ID,PASSWORD) values (227,'helloadmin');
REM INSERTING into C##ATEST.BOOK
SET DEFINE OFF;
REM INSERTING into C##ATEST.BOOKS
SET DEFINE OFF;
Insert into C##ATEST.BOOKS (BOOK_ID,PUBLISHER_ID,TITLE,AUTHOR,ISBN,NUM_OF_BOOKS) values (1,'P001','B.E.E','BALLANIS','280-2981-7892-15',56);
Insert into C##ATEST.BOOKS (BOOK_ID,PUBLISHER_ID,TITLE,AUTHOR,ISBN,NUM_OF_BOOKS) values (2,'P456','SOCIAL STUDIES','H. TAUB','4837-385-9482-88',47);
Insert into C##ATEST.BOOKS (BOOK_ID,PUBLISHER_ID,TITLE,AUTHOR,ISBN,NUM_OF_BOOKS) values (4,'P012','BIG DATA ANALYTICS','SARVESH TALE','1488-112-70498-87',78);
Insert into C##ATEST.BOOKS (BOOK_ID,PUBLISHER_ID,TITLE,AUTHOR,ISBN,NUM_OF_BOOKS) values (5,'P003','TELL TALES','RK NARAYAN','9873-721-48-44862',29);
Insert into C##ATEST.BOOKS (BOOK_ID,PUBLISHER_ID,TITLE,AUTHOR,ISBN,NUM_OF_BOOKS) values (6,'P012','HARRY POTTER','RK NARAYAN','9342-913-2222-12',50);
REM INSERTING into C##ATEST.CUSTOMER
SET DEFINE OFF;
Insert into C##ATEST.CUSTOMER (CUST_ID,NAME,EMAIL_ID,CITY,CONTACT) values ('C01','Muriel','1938212@gmail.com','New Delhi','3122011235');
Insert into C##ATEST.CUSTOMER (CUST_ID,NAME,EMAIL_ID,CITY,CONTACT) values ('C02','Sharone','shar0930@gmail.com','Mumbai','3121314634');
Insert into C##ATEST.CUSTOMER (CUST_ID,NAME,EMAIL_ID,CITY,CONTACT) values ('C03','Laurence','ljacobsyee22@gmail.com','Nagpur','09038541656');
Insert into C##ATEST.CUSTOMER (CUST_ID,NAME,EMAIL_ID,CITY,CONTACT) values ('C04','Courtney','courtneydabest@yahoo.com','Nashik','312154526');
Insert into C##ATEST.CUSTOMER (CUST_ID,NAME,EMAIL_ID,CITY,CONTACT) values ('C05','Raj','raj991@yahoo.com','Aurangabad','6722562365');
Insert into C##ATEST.CUSTOMER (CUST_ID,NAME,EMAIL_ID,CITY,CONTACT) values ('C06','Sebastian','Sebsebthegreat@gmail.com','Dadar','2782562365');
REM INSERTING into C##ATEST.CUSTOMERS
SET DEFINE OFF;
REM INSERTING into C##ATEST.ISSUE
SET DEFINE OFF;
Insert into C##ATEST.ISSUE (CUST_ID,BOOK_ID,ISSUE_DATE,RETURN_DATE,STAFF_ID) values ('C04',1,to_date('22/08/22','RR/MM/DD'),to_date('22/08/27','RR/MM/DD'),'S06');
Insert into C##ATEST.ISSUE (CUST_ID,BOOK_ID,ISSUE_DATE,RETURN_DATE,STAFF_ID) values ('C03',1,to_date('21/01/01','RR/MM/DD'),to_date('21/01/05','RR/MM/DD'),'S01');
Insert into C##ATEST.ISSUE (CUST_ID,BOOK_ID,ISSUE_DATE,RETURN_DATE,STAFF_ID) values ('C05',2,to_date('20/08/02','RR/MM/DD'),null,'S03');
Insert into C##ATEST.ISSUE (CUST_ID,BOOK_ID,ISSUE_DATE,RETURN_DATE,STAFF_ID) values ('C04',1,to_date('21/12/03','RR/MM/DD'),to_date('22/01/01','RR/MM/DD'),'S01');
Insert into C##ATEST.ISSUE (CUST_ID,BOOK_ID,ISSUE_DATE,RETURN_DATE,STAFF_ID) values ('C05',2,to_date('20/08/03','RR/MM/DD'),null,'S03');
REM INSERTING into C##ATEST.ISSUEHISTORY
SET DEFINE OFF;
REM INSERTING into C##ATEST.PUBLISHER
SET DEFINE OFF;
Insert into C##ATEST.PUBLISHER (PUBLISHER_ID,PUBLISHER_NAME) values ('P001','McGraw Hill');
Insert into C##ATEST.PUBLISHER (PUBLISHER_ID,PUBLISHER_NAME) values ('P012','Techneo');
Insert into C##ATEST.PUBLISHER (PUBLISHER_ID,PUBLISHER_NAME) values ('P003','Oxford');
Insert into C##ATEST.PUBLISHER (PUBLISHER_ID,PUBLISHER_NAME) values ('P145','BR Patil');
Insert into C##ATEST.PUBLISHER (PUBLISHER_ID,PUBLISHER_NAME) values ('P456','S Chand');
Insert into C##ATEST.PUBLISHER (PUBLISHER_ID,PUBLISHER_NAME) values ('P087','Cengage');
Insert into C##ATEST.PUBLISHER (PUBLISHER_ID,PUBLISHER_NAME) values ('P324','Black Swan');
REM INSERTING into C##ATEST.STAFF
SET DEFINE OFF;
Insert into C##ATEST.STAFF (STAFF_ID,STAFF_NAME,SALARY,PHONE,STREET) values ('S01','Eliel',3000,'9167180803','Colaba');
Insert into C##ATEST.STAFF (STAFF_ID,STAFF_NAME,SALARY,PHONE,STREET) values ('S02','Neelam',3040,'9161180803','Puri');
Insert into C##ATEST.STAFF (STAFF_ID,STAFF_NAME,SALARY,PHONE,STREET) values ('S03','Brigham',13000,'9110180803','Circular Road');
Insert into C##ATEST.STAFF (STAFF_ID,STAFF_NAME,SALARY,PHONE,STREET) values ('S04','Jacob',373000,'9169870803','Connaught Place');
Insert into C##ATEST.STAFF (STAFF_ID,STAFF_NAME,SALARY,PHONE,STREET) values ('S05','Gyuhwan',333000,'876180803','Fort');
Insert into C##ATEST.STAFF (STAFF_ID,STAFF_NAME,SALARY,PHONE,STREET) values ('S06','Sareena',333000,'9167181233','Tilak Road');
Insert into C##ATEST.STAFF (STAFF_ID,STAFF_NAME,SALARY,PHONE,STREET) values ('S07','Patrick',800,'916718233','Tilak Road1');
REM INSERTING into C##ATEST.TEST
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Trigger BOOK_BI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATEST"."BOOK_BI" 
BEFORE INSERT ON Books
FOR EACH ROW
BEGIN
  SELECT book_seq.nextval
  INTO: new.Book_ID
  FROM dual;
END;
/
ALTER TRIGGER "C##ATEST"."BOOK_BI" ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "C##ATEST"."BOOK" ADD CHECK (status in('Issued','Due','Available')) ENABLE;
  ALTER TABLE "C##ATEST"."BOOK" ADD PRIMARY KEY ("BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PUBLISHER
--------------------------------------------------------

  ALTER TABLE "C##ATEST"."PUBLISHER" MODIFY ("PUBLISHER_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ATEST"."PUBLISHER" ADD PRIMARY KEY ("PUBLISHER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ISSUEHISTORY
--------------------------------------------------------

  ALTER TABLE "C##ATEST"."ISSUEHISTORY" ADD CHECK (status in('Issued','Returned')) ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOKS
--------------------------------------------------------

  ALTER TABLE "C##ATEST"."BOOKS" MODIFY ("AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "C##ATEST"."BOOKS" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "C##ATEST"."BOOKS" ADD CHECK (Num_of_Books >= 0) ENABLE;
  ALTER TABLE "C##ATEST"."BOOKS" ADD PRIMARY KEY ("BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ATEST"."BOOKS" ADD UNIQUE ("ISBN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "C##ATEST"."STAFF" MODIFY ("STAFF_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ATEST"."STAFF" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "C##ATEST"."STAFF" ADD CHECK (Salary >= 500) ENABLE;
  ALTER TABLE "C##ATEST"."STAFF" ADD PRIMARY KEY ("STAFF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ISSUE
--------------------------------------------------------

  ALTER TABLE "C##ATEST"."ISSUE" ADD PRIMARY KEY ("CUST_ID", "BOOK_ID", "ISSUE_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "C##ATEST"."CUSTOMERS" ADD PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "C##ATEST"."TEST" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "C##ATEST"."CUSTOMER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ATEST"."CUSTOMER" ADD CHECK (Email_ID like '%@%.%') ENABLE;
  ALTER TABLE "C##ATEST"."CUSTOMER" ADD PRIMARY KEY ("CUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ATEST"."CUSTOMER" ADD UNIQUE ("CONTACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOKS
--------------------------------------------------------

  ALTER TABLE "C##ATEST"."BOOKS" ADD FOREIGN KEY ("PUBLISHER_ID")
	  REFERENCES "C##ATEST"."PUBLISHER" ("PUBLISHER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ISSUE
--------------------------------------------------------

  ALTER TABLE "C##ATEST"."ISSUE" ADD FOREIGN KEY ("BOOK_ID")
	  REFERENCES "C##ATEST"."BOOKS" ("BOOK_ID") ENABLE;
